version: 2

jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil@sha256:06450ec212b43cc103462419f271f29cff0cf67e802e63185b40a3ded02393c9
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
